parameters:
    oiv.entity.education.class: OivBundle\Entity\EducationData
    oiv.entity.naming.class: OivBundle\Entity\NamingData
    oiv.entity.stat.class: OivBundle\Entity\StatData
    oiv.entity.variety.class: OivBundle\Entity\VarietyData
    oiv.entity.parameters.class: OivBundle\Entity\Parameters

services:
    oiv.education_repository:
        class: OivBundle\Repository\EducationDataRepository
        factory: ["@doctrine", getRepository]
        arguments: [%oiv.entity.education.class%]
        
    oiv.naming_repository:
        class: OivBundle\Repository\NamingDataRepository
        factory: ["@doctrine", getRepository]
        arguments: [%oiv.entity.naming.class%]
        
    oiv.stat_repository:
        class: OivBundle\Repository\StatDataRepository
        factory: ["@doctrine", getRepository]
        arguments: [%oiv.entity.stat.class%]
        
    oiv.variety_repository:
        class: OivBundle\Repository\VarietyDataRepository
        factory: ["@doctrine", getRepository]
        arguments: [%oiv.entity.variety.class%]

    oiv.variety_repository:
        class: OivBundle\Repository\ParametersRepository
        factory: ["@doctrine", getRepository]
        arguments: [%oiv.entity.parameters.class%]
        
        
# List Handler
    oiv.handler.claculate_stat:
        class: OivBundle\Handlers\HandleCalculatedStat
        arguments: ["@monolog.logger.import_file_bdd","@doctrine"]

    oiv.handler.parameter_stat:
        class: OivBundle\Handlers\HandleParameterStat
        arguments: ["@logger","@doctrine"]

    oiv.handler.import_file:
        class: OivBundle\Handlers\HandleImportFile
        arguments: ["@logger","@doctrine","@translator"]

    oiv.handler.naming_data:
        class: OivBundle\Handlers\HandleNamingData
        arguments: ["@logger","@doctrine"]
