CibloBundle\Entity\Order:
    type: entity
    table: orders
    repositoryClass: CibloBundle\Repository\OrderRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        reference:
            type: integer
            nullable: false
            options:
                unsigned: false
        date:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        conversionRate:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: conversion_rate
        totalPaid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: total_paid
        valid:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
