CibloBundle\Entity\Visit:
    type: entity
    table: visit
    repositoryClass: CibloBundle\Repository\VisitRepository
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: date
            nullable: false
        navigateur:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        os:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        resolution:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        prepherique:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        nbVist:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nb_vist
    lifecycleCallbacks: {  }
