parameters:
    ciblo.entity.visit.class: CibloBundle\Entity\Visit
    ciblo.entity.order.class: CibloBundle\Entity\Order

services:
#    ciblo.example:
#        class: CibloBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    ciblo.customer_repository.visit:
        class: CibloBundle\Repository\VisitRepository
        factory: ["@doctrine", getRepository]
        arguments: [%ciblo.entity.visit.class%]

    ciblo.customer_repository.order:
        class: CibloBundle\Repository\OrderRepository
        factory: ["@doctrine", getRepository]
        arguments: [%ciblo.entity.order.class%]