oiv:
    resource: "@OivBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/statistiques
    requirements:
            _locale: 'fr|en'
ciblo:
    resource: "@CibloBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
