oiv:
    resource: "@OivBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/statistiques
    requirements:
            _locale: 'fr|en|es|de|it'

oiv_logout:
    path: /fr/statistiques/backoffice/logout
